/** Steam/Xbox catalog and save-rule audit, 2026-09-12. See docs/achievements.md. */
export interface AchievementDefinition {
  id: string;
  name: string;
  description: string;
  kind: 'tower' | 'captures' | 'species' | 'raid' | 'capture' | 'notes' | 'relic' | 'condensation' | 'counter' | 'craft' | 'hard' | 'research' | 'expedition' | 'areas' | 'chopper' | 'fishing' | 'lunker' | 'arena' | 'friendship' | 'tokens' | 'tree';
  target: number;
  key: string;
  group: string;
  bucket: number;
}

export const ACHIEVEMENTS: readonly AchievementDefinition[] = [
  {"id": "achievement-1", "name": "Hillside Sovereign", "description": "Defeated Zoe & Grizzbolt", "kind": "tower", "target": 1, "key": "GrassBoss", "group": "Combat", "bucket": 1},
  {"id": "achievement-2", "name": "Forest Sovereign", "description": "Defeated Lily & Lyleen", "kind": "tower", "target": 1, "key": "ForestBoss", "group": "Combat", "bucket": 1},
  {"id": "achievement-3", "name": "Desert Sovereign", "description": "Defeated Marcus & Faleris", "kind": "tower", "target": 1, "key": "DesertBoss", "group": "Combat", "bucket": 1},
  {"id": "achievement-4", "name": "Volcano Sovereign", "description": "Defeated Axel & Orserk", "kind": "tower", "target": 1, "key": "ElectricBoss", "group": "Combat", "bucket": 1},
  {"id": "achievement-5", "name": "Astral Sovereign", "description": "Defeated Victor & Shadowbeak", "kind": "tower", "target": 1, "key": "SnowBoss", "group": "Combat", "bucket": 1},
  {"id": "achievement-6", "name": "Beginning of the Legend", "description": "Caught your first Pal", "kind": "captures", "target": 1, "key": "", "group": "Capturing", "bucket": 1},
  {"id": "achievement-7", "name": "Newbie Pal Tamer", "description": "Caught 10 kinds of Pals", "kind": "species", "target": 10, "key": "", "group": "Capturing", "bucket": 1},
  {"id": "achievement-8", "name": "Intermediate Pal Tamer", "description": "Caught 20 kinds of Pals", "kind": "species", "target": 20, "key": "", "group": "Capturing", "bucket": 1},
  {"id": "achievement-9", "name": "Skilled Pal Tamer", "description": "Caught 50 kinds of Pals", "kind": "species", "target": 50, "key": "", "group": "Capturing", "bucket": 1},
  {"id": "achievement-10", "name": "Seasoned Pal Tamer", "description": "Caught 90 kinds of Pals", "kind": "species", "target": 90, "key": "", "group": "Capturing", "bucket": 1},
  {"id": "achievement-11", "name": "Twilight Siren", "description": "Defeated a summoned Bellanoir", "kind": "raid", "target": 1, "key": "PalSummon_NightLady", "group": "Combat", "bucket": 1},
  {"id": "achievement-12", "name": "Eclipsed Siren", "description": "Defeated a summoned Bellanoir Libero", "kind": "raid", "target": 1, "key": "PalSummon_NightLady_Dark", "group": "Combat", "bucket": 1},
  {"id": "achievement-13", "name": "Blossom Sovereign", "description": "Defeated Saya & Selyne", "kind": "tower", "target": 1, "key": "SakurajimaBoss", "group": "Combat", "bucket": 1},
  {"id": "achievement-14", "name": "Exceptional Pal Tamer", "description": "Caught 140 kinds of Pals", "kind": "species", "target": 140, "key": "", "group": "Capturing", "bucket": 1},
  {"id": "achievement-15", "name": "Overhunting", "description": "Caught 1000 Pals", "kind": "captures", "target": 1000, "key": "", "group": "Capturing", "bucket": 1},
  {"id": "achievement-16", "name": "Inhuman Act", "description": "Caught a Human", "kind": "capture", "target": 1, "key": "Human", "group": "Capturing", "bucket": 1},
  {"id": "achievement-17", "name": "Trail of the Castaway", "description": "Obtained 40 Notes", "kind": "notes", "target": 40, "key": "", "group": "Exploration", "bucket": 1},
  {"id": "achievement-18", "name": "Palpagos Guru", "description": "Obtained 50 Lifmunk Effigies", "kind": "relic", "target": 50, "key": "CapturePower", "group": "Exploration", "bucket": 1},
  {"id": "achievement-19", "name": "All for One", "description": "Maximized the rank of a Pal", "kind": "condensation", "target": 1, "key": "", "group": "Pal Development", "bucket": 1},
  {"id": "achievement-20", "name": "Voice of Resentment", "description": "Maximized the rank of 5 Pals", "kind": "condensation", "target": 5, "key": "", "group": "Pal Development", "bucket": 1},
  {"id": "achievement-21", "name": "Senior Adventurer", "description": "Cleared 20 dungeons", "kind": "counter", "target": 20, "key": "normal_dungeon_clears", "group": "Exploration", "bucket": 2},
  {"id": "achievement-22", "name": "Conqueror of the Sea", "description": "Seized the Oil Rig", "kind": "counter", "target": 1, "key": "oilrig_clears", "group": "Combat", "bucket": 1},
  {"id": "achievement-23", "name": "Sphere Craftsman", "description": "Crafted 2,000 spheres", "kind": "craft", "target": 2000, "key": "SPWeaponCaptureBall", "group": "Crafting", "bucket": 2},
  {"id": "achievement-24", "name": "Iron Heart", "description": "Crafted 10,000 ingots", "kind": "craft", "target": 10000, "key": "MaterialIngot", "group": "Crafting", "bucket": 2},
  {"id": "achievement-25", "name": "Blood and Iron", "description": "Crafted 20,000 ammo", "kind": "craft", "target": 20000, "key": "ConsumeBullet", "group": "Crafting", "bucket": 2},
  {"id": "achievement-26", "name": "Incarnation of the Eternal Flame", "description": "Defeated a summoned Blazamut Ryu", "kind": "raid", "target": 1, "key": "PalSummon_KingBahamut_Dragon", "group": "Combat", "bucket": 1},
  {"id": "achievement-27", "name": "Legendary Celestial Dragon", "description": "Caught a Jetragon", "kind": "capture", "target": 1, "key": "JetDragon", "group": "Capturing", "bucket": 1},
  {"id": "achievement-28", "name": "Holy Knight of Legend", "description": "Caught a Paladius", "kind": "capture", "target": 1, "key": "SaintCentaur", "group": "Capturing", "bucket": 1},
  {"id": "achievement-29", "name": "Dark Knight of Legend", "description": "Caught a Necromus", "kind": "capture", "target": 1, "key": "BlackCentaur", "group": "Capturing", "bucket": 1},
  {"id": "achievement-30", "name": "Legendary Steed of Ice", "description": "Caught a Frostallion", "kind": "capture", "target": 1, "key": "IceHorse", "group": "Capturing", "bucket": 1},
  {"id": "achievement-31", "name": "Champion of the Palpagos Islands", "description": "Defeated 6 tower bosses in Hard Mode", "kind": "hard", "target": 6, "key": "", "group": "Combat", "bucket": 2},
  {"id": "achievement-32", "name": "Feybreak Sovereign", "description": "Defeated Bjorn & Bastigor", "kind": "tower", "target": 1, "key": "VikingBoss", "group": "Combat", "bucket": 1},
  {"id": "achievement-33", "name": "Invader from Space", "description": "Defeated a summoned Xenolord", "kind": "raid", "target": 1, "key": "PalSummon_DarkMechaDragon", "group": "Combat", "bucket": 1},
  {"id": "achievement-34", "name": "Palpagos Guardian", "description": "Obtained 100 Lifmunk Effigies", "kind": "relic", "target": 100, "key": "CapturePower", "group": "Exploration", "bucket": 1},
  {"id": "achievement-35", "name": "Pal Labor Student", "description": "Completed 10 Pal Labor Research projects", "kind": "research", "target": 10, "key": "", "group": "Guild", "bucket": 1},
  {"id": "achievement-36", "name": "Pal Labor Researcher", "description": "Completed 30 Pal Labor Research projects", "kind": "research", "target": 30, "key": "", "group": "Guild", "bucket": 1},
  {"id": "achievement-37", "name": "Pal Labor Professor", "description": "Completed 70 Pal Labor Research projects", "kind": "research", "target": 70, "key": "", "group": "Guild", "bucket": 1},
  {"id": "achievement-38", "name": "Novice Pal Dispatcher", "description": "Undertook 10 Pal Expeditions", "kind": "expedition", "target": 10, "key": "", "group": "Guild", "bucket": 1},
  {"id": "achievement-39", "name": "Elite Pal Dispatcher", "description": "Undertook 20 Pal Expeditions", "kind": "expedition", "target": 20, "key": "", "group": "Guild", "bucket": 1},
  {"id": "achievement-40", "name": "Freshman Surveyor", "description": "Found 10 new areas", "kind": "areas", "target": 10, "key": "", "group": "Exploration", "bucket": 1},
  {"id": "achievement-41", "name": "Junior Surveyor", "description": "Found 30 new areas", "kind": "areas", "target": 30, "key": "", "group": "Exploration", "bucket": 1},
  {"id": "achievement-42", "name": "Senior Surveyor", "description": "Found 70 new areas", "kind": "areas", "target": 70, "key": "", "group": "Exploration", "bucket": 1},
  {"id": "achievement-43", "name": "Predator Hunter", "description": "Defeated a Predator Pal", "kind": "counter", "target": 1, "key": "predator_defeats", "group": "Combat", "bucket": 2},
  {"id": "achievement-44", "name": "No-Fly Zone", "description": "Defeated Attack Chopper", "kind": "chopper", "target": 1, "key": "", "group": "Combat", "bucket": 1},
  {"id": "achievement-45", "name": "Novice Angler", "description": "Reeled in 10 Pals", "kind": "fishing", "target": 10, "key": "", "group": "Capturing", "bucket": 1},
  {"id": "achievement-46", "name": "Seasoned Angler", "description": "Reeled in 30 Pals", "kind": "fishing", "target": 30, "key": "", "group": "Capturing", "bucket": 1},
  {"id": "achievement-47", "name": "Veteran Angler", "description": "Reeled in 50 Pals", "kind": "fishing", "target": 50, "key": "", "group": "Capturing", "bucket": 1},
  {"id": "achievement-48", "name": "Lunker Hunter", "description": "Reeled in 1 Lunker", "kind": "lunker", "target": 1, "key": "", "group": "Capturing", "bucket": 1},
  {"id": "achievement-49", "name": "Silver Champ", "description": "Reached Silver Rank in the Arena", "kind": "arena", "target": 300, "key": "", "group": "Arena", "bucket": 3},
  {"id": "achievement-50", "name": "Arena Champion", "description": "Reached Master Rank in the Arena", "kind": "arena", "target": 3800, "key": "", "group": "Arena", "bucket": 3},
  {"id": "achievement-51", "name": "Best Friends Forever", "description": "Reached Trust level 10 with a Pal", "kind": "friendship", "target": 10, "key": "", "group": "Pal Development", "bucket": 1},
  {"id": "achievement-52", "name": "Successful Infiltration", "description": "Cleared 1 enemy faction base", "kind": "counter", "target": 1, "key": "camps_conquered", "group": "Combat", "bucket": 1},
  {"id": "achievement-53", "name": "Unstoppable Streak", "description": "Cleared 10 enemy faction bases", "kind": "counter", "target": 10, "key": "camps_conquered", "group": "Combat", "bucket": 1},
  {"id": "achievement-54", "name": "A Nose for Treasure", "description": "Found 5 treasures with Treasure Maps", "kind": "counter", "target": 5, "key": "treasures_found", "group": "Exploration", "bucket": 1},
  {"id": "achievement-55", "name": "Rookie Pal Slayer", "description": "Obtained 5 Pal Bounty Tokens", "kind": "tokens", "target": 5, "key": "", "group": "Combat", "bucket": 1},
  {"id": "achievement-56", "name": "Alpha Pal Slayer", "description": "Obtained 20 Pal Bounty Tokens", "kind": "tokens", "target": 20, "key": "", "group": "Combat", "bucket": 1},
  {"id": "achievement-57", "name": "King of Salvation", "description": "Defeated a summoned Hartalis", "kind": "raid", "target": 1, "key": "PalSummon_LegendDeer", "group": "Combat", "bucket": 1},
  {"id": "achievement-58", "name": "Forest Guru", "description": "Obtained 20 Lamball Effigies", "kind": "relic", "target": 20, "key": "HungerReduction", "group": "Exploration", "bucket": 1},
  {"id": "achievement-59", "name": "Volcano Guru", "description": "Obtained 20 Pengullet Effigies", "kind": "relic", "target": 20, "key": "SwimSpeed", "group": "Exploration", "bucket": 1},
  {"id": "achievement-60", "name": "Desert Guru", "description": "Obtained 20 Munchill Effigies", "kind": "relic", "target": 20, "key": "FoodDecayReduction", "group": "Exploration", "bucket": 1},
  {"id": "achievement-61", "name": "Snowy Mountain Guru", "description": "Obtained 20 Rooby Effigies", "kind": "relic", "target": 20, "key": "JumpPower", "group": "Exploration", "bucket": 1},
  {"id": "achievement-62", "name": "Sakurajima Guru", "description": "Obtained 20 Herbil Effigies", "kind": "relic", "target": 20, "key": "GliderSpeed", "group": "Exploration", "bucket": 1},
  {"id": "achievement-63", "name": "Feybreak Guru", "description": "Obtained 20 Tanzee Effigies", "kind": "relic", "target": 20, "key": "ClimbSpeed", "group": "Exploration", "bucket": 1},
  {"id": "achievement-64", "name": "Sunreach Guru", "description": "Obtained 20 Depresso Effigies", "kind": "relic", "target": 20, "key": "StatusAilmentResist", "group": "Exploration", "bucket": 1},
  {"id": "achievement-65", "name": "World Tree Guru", "description": "Obtained 20 Cattiva Effigies", "kind": "relic", "target": 20, "key": "StaminaReduction", "group": "Exploration", "bucket": 1},
  {"id": "achievement-66", "name": "Forest Traveler", "description": "Obtained 4 Lunaris Effigies", "kind": "relic", "target": 4, "key": "SphereHoming", "group": "Exploration", "bucket": 1},
  {"id": "achievement-67", "name": "Island Traveler", "description": "Obtained 4 Relaxaurus Effigies", "kind": "relic", "target": 4, "key": "ExpBonus", "group": "Exploration", "bucket": 1},
  {"id": "achievement-68", "name": "World Traveler", "description": "Obtained 4 Yakumo Effigies", "kind": "relic", "target": 4, "key": "RainbowPassiveRate", "group": "Exploration", "bucket": 1},
  {"id": "achievement-69", "name": "Meddling With Mutation", "description": "Mutated a Pal for the first time", "kind": "counter", "target": 1, "key": "mutations", "group": "Pal Development", "bucket": 1},
  {"id": "achievement-70", "name": "Hidden Potential", "description": "Awakened a Pal for the first time", "kind": "counter", "target": 1, "key": "awakenings", "group": "Pal Development", "bucket": 1},
  {"id": "achievement-71", "name": "Arena Legend", "description": "Reached legend rank in the arena", "kind": "arena", "target": 6000, "key": "", "group": "Arena", "bucket": 3},
  {"id": "achievement-72", "name": "To the World Tree", "description": "Set foot within the World Tree", "kind": "tree", "target": 1, "key": "", "group": "Exploration", "bucket": 2},
  {"id": "achievement-73", "name": "Sunreach Sovereign", "description": "Defeated Auri & Shaolong", "kind": "tower", "target": 1, "key": "SorajimaBoss", "group": "Combat", "bucket": 1},
  {"id": "achievement-74", "name": "Legendary Ocean King", "description": "Caught a Panthalus", "kind": "capture", "target": 1, "key": "KingWhale", "group": "Capturing", "bucket": 1},
  {"id": "achievement-75", "name": "Savior of Palpagos", "description": "Defeated Astralym", "kind": "tower", "target": 1, "key": "WorldTreeBoss", "group": "Combat", "bucket": 1},
];

export const ACHIEVEMENT_ITEM_TYPES: Record<string, readonly string[]> = {
  "MaterialIngot": [
    "Charcoal",
    "CopperIngot",
    "IronIngot",
    "ManganeseIngot",
    "Plastic",
    "SkyislandIngot",
    "StainlessSteel",
    "StealIngot",
    "WorldTreeIngot",
    "YakushimaIngot001",
    "YakushimaIngot002"
  ],
  "SPWeaponCaptureBall": [
    "PalSphere",
    "PalSphere_Ancient_1",
    "PalSphere_Ancient_2",
    "PalSphere_Exotic",
    "PalSphere_Giga",
    "PalSphere_Legend",
    "PalSphere_Master",
    "PalSphere_Mega",
    "PalSphere_Robbery",
    "PalSphere_Tera",
    "PalSphere_Ultimate"
  ],
  "ConsumeBullet": [
    "Arrow",
    "Arrow_Fire",
    "Arrow_Poison",
    "AssaultRifleBullet",
    "BeamLauncherBullet",
    "ChargeLaserRifleBullet",
    "ElectricArcAssaultRifleBullet",
    "EnergyLauncherBullet",
    "EnergyShotgunBullet",
    "ExplosiveBullet",
    "FlamethrowerBullet",
    "GatlingBullet",
    "GrenadeBullet",
    "HandgunBullet",
    "InkBullet",
    "LaserBullet",
    "LaserGatlingBullet",
    "MachingunBullet",
    "MagnumBullet",
    "MeteorBullet",
    "MissileBullet",
    "OverheatRifleBullet",
    "PalDopingShotBullet",
    "ReinforcedArrow",
    "RifleBullet",
    "RoughBullet",
    "SFArrow",
    "ShotgunBullet",
    "SkyAssaultRifleBullet",
    "SkyBowArrow",
    "SkyGrenadeLauncherBullet",
    "SkyShotgunBullet",
    "SkySubmachineGunBullet",
    "WidePenetrateShotgunBullet"
  ],
  "Essential_BossReward": [
    "BossDefeatReward_AmaterasuWolf_Dark",
    "BossDefeatReward_Anubis",
    "BossDefeatReward_BadCatgirl",
    "BossDefeatReward_BerryGoat_Dark",
    "BossDefeatReward_BlackMetalDragon",
    "BossDefeatReward_BlackPuppy",
    "BossDefeatReward_BlueDragon",
    "BossDefeatReward_BlueThunderHorse",
    "BossDefeatReward_BlueberryFairy",
    "BossDefeatReward_BossRush",
    "BossDefeatReward_CactusDoll",
    "BossDefeatReward_CaptainPenguin",
    "BossDefeatReward_CatMage",
    "BossDefeatReward_CatVampire",
    "BossDefeatReward_CubeTurtle",
    "BossDefeatReward_CubeTurtle_Neutral",
    "BossDefeatReward_DarkScorpion",
    "BossDefeatReward_DarkScorpion_Ground",
    "BossDefeatReward_DomeArmorDragon",
    "BossDefeatReward_ElecLizard",
    "BossDefeatReward_ElecPanda",
    "BossDefeatReward_ElecSnail",
    "BossDefeatReward_FairyDragon",
    "BossDefeatReward_FengyunDeeper",
    "BossDefeatReward_FengyunDeeper_Electric",
    "BossDefeatReward_FireKirin",
    "BossDefeatReward_FlameBuffalo",
    "BossDefeatReward_FlowerDinosaur_Electric",
    "BossDefeatReward_FlowerDoll",
    "BossDefeatReward_FlowerPrince",
    "BossDefeatReward_FoxExorcist",
    "BossDefeatReward_FoxMage",
    "BossDefeatReward_GhostDragon",
    "BossDefeatReward_GhostRabbit",
    "BossDefeatReward_GoldenHorse",
    "BossDefeatReward_GrassGolem",
    "BossDefeatReward_GrassGolem_Dark",
    "BossDefeatReward_GrassMammoth",
    "BossDefeatReward_GrassPanda_Electric",
    "BossDefeatReward_GrassRabbitMan",
    "BossDefeatReward_GrimGirl",
    "BossDefeatReward_HawkBird",
    "BossDefeatReward_HerculesBeetle",
    "BossDefeatReward_HerculesBeetle_Ground",
    "BossDefeatReward_Horus_Water",
    "BossDefeatReward_IceFox",
    "BossDefeatReward_IceHorse",
    "BossDefeatReward_IceHorse_Dark",
    "BossDefeatReward_IceNarwhal",
    "BossDefeatReward_IceNarwhal_Fire",
    "BossDefeatReward_JetDragon",
    "BossDefeatReward_KabukiMan",
    "BossDefeatReward_KingAlpaca",
    "BossDefeatReward_KingAlpaca_Ice",
    "BossDefeatReward_KingBahamut",
    "BossDefeatReward_Kirin",
    "BossDefeatReward_Kitsunebi_Ice",
    "BossDefeatReward_LazyCatfish",
    "BossDefeatReward_LazyDragon_Electric",
    "BossDefeatReward_LilyQueen",
    "BossDefeatReward_LilyQueen_Dark",
    "BossDefeatReward_LotusDragon",
    "BossDefeatReward_Manticore",
    "BossDefeatReward_MoonChild",
    "BossDefeatReward_MopKing",
    "BossDefeatReward_Mothman",
    "BossDefeatReward_MushroomLady",
    "BossDefeatReward_Mutant",
    "BossDefeatReward_MysteryMask",
    "BossDefeatReward_NaughtyCat",
    "BossDefeatReward_NightBlueHorse",
    "BossDefeatReward_PinkRabbit_Grass",
    "BossDefeatReward_PlantSlime",
    "BossDefeatReward_PoseidonOrca",
    "BossDefeatReward_PurpleSpider",
    "BossDefeatReward_QueenBee",
    "BossDefeatReward_RaijinDaughter_Water",
    "BossDefeatReward_RockBeast",
    "BossDefeatReward_RockBeast_Ice",
    "BossDefeatReward_Ronin",
    "BossDefeatReward_SaintCentaur",
    "BossDefeatReward_SakuraSaurus",
    "BossDefeatReward_SakuraSaurus_Water",
    "BossDefeatReward_ScorpionMan_Electric",
    "BossDefeatReward_SkyDragon",
    "BossDefeatReward_Suzaku",
    "BossDefeatReward_ThunderBird",
    "BossDefeatReward_ThunderFluffyBird",
    "BossDefeatReward_Umihebi",
    "BossDefeatReward_VioletFairy",
    "BossDefeatReward_VolcanicMonster",
    "BossDefeatReward_VolcanoDragon",
    "BossDefeatReward_VolcanoDragon_Ice",
    "BossDefeatReward_WeaselDragon",
    "BossDefeatReward_Werewolf_Ice",
    "BossDefeatReward_WhiteDeer",
    "BossDefeatReward_WhiteDeer_Dark",
    "BossDefeatReward_WhiteMoth",
    "BossDefeatReward_WhiteShieldDragon",
    "BossDefeatReward_WhiteTiger_Ground",
    "BossDefeatReward_WingGolem",
    "BossDefeatReward_Yeti_Grass"
  ]
};

export const ACHIEVEMENT_ITEM_REDIRECTS: Record<string, string> = {
  "Accessory_AT_2": "Accessory_AT_1",
  "Accessory_AT_3": "Accessory_AT_1",
  "Accessory_AquaResist_2": "Accessory_AquaResist_1",
  "Accessory_AquaResist_3": "Accessory_AquaResist_1",
  "Accessory_CoolResist_2": "Accessory_CoolResist_1",
  "Accessory_CoolResist_3": "Accessory_CoolResist_1",
  "Accessory_DarkResist_2": "Accessory_DarkResist_1",
  "Accessory_DarkResist_3": "Accessory_DarkResist_1",
  "Accessory_DragonResist_2": "Accessory_DragonResist_1",
  "Accessory_DragonResist_3": "Accessory_DragonResist_1",
  "Accessory_EarthResist_2": "Accessory_EarthResist_1",
  "Accessory_EarthResist_3": "Accessory_EarthResist_1",
  "Accessory_FireResist_2": "Accessory_FireResist_1",
  "Accessory_FireResist_3": "Accessory_FireResist_1",
  "Accessory_HP_2": "Accessory_HP_1",
  "Accessory_HP_3": "Accessory_HP_1",
  "Accessory_HeatColdResist_2": "Accessory_HeatColdResist_1",
  "Accessory_HeatColdResist_3": "Accessory_HeatColdResist_1",
  "Accessory_HeatResist_2": "Accessory_HeatResist_1",
  "Accessory_HeatResist_3": "Accessory_HeatResist_1",
  "Accessory_IceResist_2": "Accessory_IceResist_1",
  "Accessory_IceResist_3": "Accessory_IceResist_1",
  "Accessory_LeafResist_2": "Accessory_LeafResist_1",
  "Accessory_LeafResist_3": "Accessory_LeafResist_1",
  "Accessory_MaxWeightUp_02": "Accessory_MaxWeightUp_01",
  "Accessory_MaxWeightUp_03": "Accessory_MaxWeightUp_01",
  "Accessory_NormalResist_2": "Accessory_NormalResist_1",
  "Accessory_NormalResist_3": "Accessory_NormalResist_1",
  "Accessory_ThunderResist_2": "Accessory_ThunderResist_1",
  "Accessory_ThunderResist_3": "Accessory_ThunderResist_1",
  "Accessory_WorkSpeed_2": "Accessory_WorkSpeed_1",
  "Accessory_WorkSpeed_3": "Accessory_WorkSpeed_1",
  "Accessory_defense_2": "Accessory_defense_1",
  "Accessory_defense_3": "Accessory_defense_1",
  "Otomo_Attack_up2": "Otomo_Attack_up1",
  "Otomo_Attack_up3": "Otomo_Attack_up1",
  "Otomo_Defense_up2": "Otomo_Defense_up1",
  "Otomo_Defense_up3": "Otomo_Defense_up1",
  "Otomo_ElementBoost_Dark_2": "Otomo_ElementBoost_Dark_1",
  "Otomo_ElementBoost_Dark_3": "Otomo_ElementBoost_Dark_1",
  "Otomo_ElementBoost_Dragon_2": "Otomo_ElementBoost_Dragon_1",
  "Otomo_ElementBoost_Dragon_3": "Otomo_ElementBoost_Dragon_1",
  "Otomo_ElementBoost_Earth_2": "Otomo_ElementBoost_Earth_1",
  "Otomo_ElementBoost_Earth_3": "Otomo_ElementBoost_Earth_1",
  "Otomo_ElementBoost_Electricity_2": "Otomo_ElementBoost_Electricity_1",
  "Otomo_ElementBoost_Electricity_3": "Otomo_ElementBoost_Electricity_1",
  "Otomo_ElementBoost_Fire_2": "Otomo_ElementBoost_Fire_1",
  "Otomo_ElementBoost_Fire_3": "Otomo_ElementBoost_Fire_1",
  "Otomo_ElementBoost_Ice_2": "Otomo_ElementBoost_Ice_1",
  "Otomo_ElementBoost_Ice_3": "Otomo_ElementBoost_Ice_1",
  "Otomo_ElementBoost_Leaf_2": "Otomo_ElementBoost_Leaf_1",
  "Otomo_ElementBoost_Leaf_3": "Otomo_ElementBoost_Leaf_1",
  "Otomo_ElementBoost_Normal_2": "Otomo_ElementBoost_Normal_1",
  "Otomo_ElementBoost_Normal_3": "Otomo_ElementBoost_Normal_1",
  "Otomo_ElementBoost_Water_2": "Otomo_ElementBoost_Water_1",
  "Otomo_ElementBoost_Water_3": "Otomo_ElementBoost_Water_1",
  "Otomo_PalExp_Increase_2": "Otomo_PalExp_Increase_1",
  "Otomo_PalExp_Increase_3": "Otomo_PalExp_Increase_1"
};
